version: '3.4'

services:
  vismaidella.personapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=mariadb;Database=persons_db;Uid=root;Pwd=root;
      - ConnectionStrings__Redis=redis
    ports:
      - 5000:80

  mariadb:
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root

  redis:
    ports:
      - 6379:6379
