version: '3.4'

services:
  vismaidella.personapi:
    image: ${DOCKER_REGISTRY-}vismaidellapersonapi
    restart: always
    build:
      context: .
      dockerfile: VismaIdella.PersonApi/Dockerfile
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data


volumes:
  mariadb_data:
  redis_data:
